# Generated by Django 2.1.1 on 2018-09-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchbar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
